name: ci/cd pipeline to deploy to tomcat
on: 
  push:
    branches: master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: set-up jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'   # Updated Java version
      - name: validate with maven
        run: mvn validate
      - name: compile with maven
        run: mvn compile
      - name: test with maven
        run: mvn test
      - name: package with maven
        run: mvn package
     
        # Deploy to Tomcat-Dev
      - name: deploy war to tomcat
        run: | 
                curl -v -u ${{ secrets.TOMCAT_USER_Dev }}:${{ secrets.TOMCAT_PASSWORD_Dev }} \
                  -T target/TrainBook-1.0.0-SNAPSHOT.war \
                  "http://${{ secrets.TOMCAT_HOST_Dev }}:8080/manager/text/deploy?path=/TrainBook&update=true"
        
        # Deploy to Tomcat-test
      - name: deploy war to tomcat
        run: | 
                curl -v -u ${{ secrets.TOMCAT_USER_test }}:${{ secrets.TOMCAT_PASSWORD_test }} \
                  -T target/TrainBook-1.0.0-SNAPSHOT.war \
                  "http://${{ secrets.TOMCAT_HOST_test }}:8080/manager/text/deploy?path=/TrainBook&update=true"
 
     
     # Deploy to Tomcat
      - name: deploy war to tomcat
        run: | 
                curl -v -u ${{ secrets.TOMCAT_USER_Pre_Prod }}:${{ secrets.TOMCAT_PASSWORD_Pre_Prod }} \
                  -T target/TrainBook-1.0.0-SNAPSHOT.war \
                  "http://${{ secrets.TOMCAT_HOST_Pre_Prod }}:8080/manager/text/deploy?path=/TrainBook&update=true"


    # Deploy to Tomcat
      - name: deploy war to tomcat
        run: | 
                curl -v -u ${{ secrets.TOMCAT_USER_Prod }}:${{ secrets.TOMCAT_PASSWORD_prod }} \
                  -T target/TrainBook-1.0.0-SNAPSHOT.war \
                  "http://${{ secrets.TOMCAT_HOST_prod }}:8080/manager/text/deploy?path=/TrainBook&update=true"
 
